apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tim
  namespace: jupyter
subjects:
- kind: User
  name: tim
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
